version: '3.8'

services:
  postgres:
    image: postgres:16-alpine  # or postgres:15-alpine
    container_name: calendar-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: calendar-server-db
      TZ: America/New_York
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
